### ISSUE TITLE
Error when running

### ISSUE THREAD

**Issue by nolandubeau** [Sebmaster/racer-example#1]
Hi there,

First off, thanks for putting this example together.  I setup a mongolab db and I have a local redis instance running on port 6379.

when i run the node app I am able to browse to the Todo form, however when I try to add an entry Node prints out this error:

Error: Cannot use a writeConcern without a provided callback
    at Db.ensureIndex (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/db.js:1218:11)
    at Collection.ensureIndex (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/collection.js:1094:11)
    at EventEmitter.<anonymous> (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/lib/mongoskin/utils.js:68:23)
    at EventEmitter.g (events.js:175:14)
    at EventEmitter.emit (events.js:98:17)
    at null.<anonymous> (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/lib/mongoskin/collection.js:129:24)
    at Db.collection (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/db.js:484:44)
    at null.<anonymous> (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/lib/mongoskin/collection.js:119:12)
    at SkinDb.open (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/lib/mongoskin/db.js:79:19)
    at SkinCollection.open (/Library/WebServer/Documents/racer-example/node_modules/livedb-mongo/node_modules/mongoskin/lib/mongoskin/collection.js:114:19)

I also see a failed GET request in Chrome console which prints out:

GET http://localhost:8081/channel/test?OSID=5iy6efx9&OAID=2&VER=8&MODE=init&zx=jv5oxj5lng2p&t=1  bcsocket-uncompressed.js:1818

Thanks!

Nolan

**Comment by Sebmaster** [comment]
Sorry it took so long, I needed time to re-setup the dev environment.

I first thought there could be some incompatibilities with new versions of racer, but I tried running the server just now and it works fine.

Is there an entries collection in the mongo db? If not, could you try to create it and try again?

**Comment by Sebmaster** [comment]
Ah, I can see an error now, it's a different one than yours though.

I get `Modifiers and non-modifiers cannot be mixed`. I think this is because the object which is added to the collection is modified by angular.js to include the `$hashKey` property for example, before the change is submitted to the server. When it gets submitted, it will contain the `$hashKey` property and the server will block the query because it contains a key with a dollar sign.

I think I need to clone the object before submitting it to the server. I'll investigate a bit in that direction.

**Comment by Sebmaster** [comment]
Okay, I pushed bb93bcabecec53cc847e9b74985746adf41d05c4 to fix the bug I encountered. Please try again with the updated version.

**Comment by nolandubeau** [comment]
Hey Sebastian!

Thanks for the updates :)  I was initially trying to connect to a redis db
on nodejitsu and had changed the way redis was being connected so maybe
that we the issue.  I created a nano account at redistogo and all is
working now.  very cool!

I'm eventually going to start building an app using node and the couchbase.
 do you think the same approach would work with couchbase instead of redis?

I haven't read through the racer documentation fully, however was wondering
why it is necessary to have both a mongo db and redis db configured?

Thanks!

On Thu, Sep 5, 2013 at 4:16 PM, Sebastian Mayr notifications@github.comwrote:

> Okay, I pushed bb93bcahttps://github.com/Sebmaster/racer-example/commit/bb93bcabecec53cc847e9b74985746adf41d05c4to fix the bug I encountered. Please try again with the updated version.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Sebmaster/racer-example/issues/1#issuecomment-23898189
> .

## 

*Nolan Dubeau
*VP, Product Engineering, Guardly Corp.
Online: https://www.guardly.com
LinkedIn: http://www.linkedin.com/in/nolandubeau
20 Maud Street, Suite 207, Toronto, ON M5V 2M5
CA (416) 434-8029  |  US (650) 262-3599  |  Skype: nolandubeau
Please consider the environment before printing this email.

**Comment by Sebmaster** [comment]
That's good to hear.

Racer.js uses the mongodb as a permanent storage, and redis for its pubsub system as far as I know. I think the redis dependency stems from a dependency on [livedb](https://github.com/share/livedb). In the livedb issue tracker there's a [bug](https://github.com/share/livedb/issues/2) whose goal is to make redis optional.

However, even if this bug got fixed, this would only work in a single-node-server usecase! If you'd want to scale to multiple processes this wouldn't work, but you'd have to make livedb compatible with your couchbase database instead.

**Comment by nolandubeau** [comment]
Why would this not scale and only be limited to a single note process?  Are
you saying if the app was clustered horizontally it wouldn't work the same
way?

Thanks!

On Saturday, September 7, 2013, Sebastian Mayr wrote:

> That's good to hear.
> 
> Racer.js uses the mongodb as a permanent storage, and redis for its pubsub
> system as far as I know. I think the redis dependency stems from a
> dependency on livedb https://github.com/share/livedb. In the livedb
> issue tracker there's a bug https://github.com/share/livedb/issues/2whose goal is to make redis optional.
> 
> However, even if this bug got fixed, this would only work in a
> single-node-server usecase! If you'd want to scale to multiple processes
> this wouldn't work, but you'd have to make livedb compatible with your
> couchbase database instead.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Sebmaster/racer-example/issues/1#issuecomment-23995670
> .

## 

*Nolan Dubeau
*VP, Product Engineering, Guardly Corp.
Online: https://www.guardly.com
LinkedIn: http://www.linkedin.com/in/nolandubeau
20 Maud Street, Suite 207, Toronto, ON M5V 2M5
CA (416) 434-8029  |  US (650) 262-3599  |  Skype: nolandubeau
Please consider the environment before printing this email.

**Comment by Sebmaster** [comment]
As far as I unterstood, livedb uses the redis server to synchronize the document transformations. Without a central synchronization point the documents wouldn't be in sync across the different node processes.

**Comment by nolandubeau** [comment]
Ahh okay.  I think I misunderstood.  With redis or other db in place,
scaling /sync is possible but with redis as an optional config sync is not
always possible.  Correct ?

On Saturday, September 7, 2013, Sebastian Mayr wrote:

> As far as I unterstood, livedb uses the redis server to synchronize the
> document transformations. Without a central synchronization point the
> documents wouldn't be in sync across the different node processes.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Sebmaster/racer-example/issues/1#issuecomment-23999290
> .

## 

*Nolan Dubeau
*VP, Product Engineering, Guardly Corp.
Online: https://www.guardly.com
LinkedIn: http://www.linkedin.com/in/nolandubeau
20 Maud Street, Suite 207, Toronto, ON M5V 2M5
CA (416) 434-8029  |  US (650) 262-3599  |  Skype: nolandubeau
Please consider the environment before printing this email.

**Comment by Sebmaster** [comment]
Exactly.

**Comment by nolandubeau** [comment]
Thanks!

On Saturday, September 7, 2013, Sebastian Mayr wrote:

> Exactly.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/Sebmaster/racer-example/issues/1#issuecomment-24000164
> .

## 

*Nolan Dubeau
*VP, Product Engineering, Guardly Corp.
Online: https://www.guardly.com
LinkedIn: http://www.linkedin.com/in/nolandubeau
20 Maud Street, Suite 207, Toronto, ON M5V 2M5
CA (416) 434-8029  |  US (650) 262-3599  |  Skype: nolandubeau
Please consider the environment before printing this email.
